### ISSUE TITLE
OneTrainer not starting if updated, on runpod

### ISSUE THREAD

**Issue by sdk401** [ai-dock/onetrainer#1]
First of all, "auto-update" variable is set to "false" by default, so the installed OneTraineris out of date. When I changed it to "true", OneTrainer broke, does not start and gives this error in the log:

Traceback (most recent call last):
  File "/workspace/OneTrainer/scripts/train_ui.py", line 5, in
    from modules.ui.TrainUI import TrainUI
  File "/workspace/OneTrainer/modules/ui/TrainUI.py", line 12, in
    from modules.trainer.GenericTrainer import GenericTrainer
  File "/workspace/OneTrainer/modules/trainer/GenericTrainer.py", line 20, in
    from modules.dataLoader.BaseDataLoader import BaseDataLoader
  File "/workspace/OneTrainer/modules/dataLoader/BaseDataLoader.py", line 6, in
    from modules.dataLoader.mixin.DataLoaderMgdsMixin import DataLoaderMgdsMixin
  File "/workspace/OneTrainer/modules/dataLoader/mixin/DataLoaderMgdsMixin.py", line 6, in
    from mgds.PipelineModule import PipelineState
ImportError: cannot import name 'PipelineState' from 'mgds.PipelineModule' (/opt/OneTrainer/src/mgds/src/mgds/PipelineModule.py)

Tried with couple of different pods with same result.

**Comment by robballantyne** [comment]
Yeah it's broken and I haven't updated it lately because the underlying desktop image needed drastic improvement.  Fortunately, that's about done so should get some attention over the next few days

**Comment by sdk401** [comment]
Thanks! Would be nice to have updated version.

**Comment by gitwittidbit** [comment]
I am running this locally and I am not updating it but am getting the same error message. Everything works up to the point when I click on OneTrainer on the desktop. It briefly opens and then closes again and at about the same time I am seeing error message OP posted above in the logs.

Is this the same issue or is there a new problem?

**Comment by leinad13** [comment]
Any update on this? The image is great - but I need to use a newer version of OneTrainer

**Comment by robballantyne** [comment]
> Any update on this? The image is great - but I need to use a newer version of OneTrainer

If running in cloud it's probably better to run the Linux Desktop image and manually install one trainer.  I will update this image eventually but it may be better if I provide install scripts for the base Desktop instead.  That will be easier to maintain. Would that work for you?

**Comment by Ethorbit** [comment]
In my opinion this image is useless if it's broken and the suggestion is to install a different image and setup OneTrainer manually.

I think it should be archived and marked broken so as to avoid wasting people's time.

[Just made my own Docker image for running OneTrainer through the browser](https://github.com/Ethorbit/onetrainer-docker-webui). It leverages KasmVNC.
